---
title: "county.Rmd"
author: "Jackson Roe"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
```
This map shows the racial geography of the county I live in, Franklin County, OH. 
```{r}
load_variables(2018, "acs5") |> filter(concept == "RACE")

racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005",
              Hispanic = "B03003_003")

county_data <- get_acs(geography = "tract",
        variables = racevars, 
        year = 2018,
        state = "OH",
        county = "Franklin County",
        geometry = TRUE,
        summary_var = "B02001_001")

county_data |> 
  mutate(Percent = 100 * (estimate / summary_est)) |> 
  ggplot(aes(fill = Percent, color = Percent)) + 
  facet_wrap(~variable) +
  geom_sf() + 
  scale_fill_viridis_c(direction = -1) + 
  scale_color_viridis_c(direction = -1) + 
  labs(title = "Racial geography of Franklin County, Ohio",
       caption = "Source: American Community Survey 2014-2018") +
  theme_void()
```




