---
title: "Rural.Rmd"
author: "Jackson Roe"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
get_decennial(geography = "state", 
              variables = c("P001001", "P002005"), 
              year = 2010, 
              output =  "wide", 
              geometry = TRUE)
```

```{r}
rural |> 
  filter(! NAME %in% c("Alaska", "Hawaii", "Puerto Rico")) |>
  ggplot(aes(fill = 100 * P002005 / P001001)) + 
  geom_sf() + 
  scale_fill_viridis_c(option = "plasma",
                         direction = -1) + 
  labs(title = "Rural geography of the United States",
         caption = "Source: Census 2010",
         fill = "Percent Rural") +
    theme_void()
```

```{r}
get_decennial(geography = "state", 
              variables = c("P001001", "P002005"), 
              year = 2010, 
              output =  "wide", 
              geometry = TRUE)

rural_shifted <- rural |> 
  shift_geometry() |>
  ggplot(aes(fill = 100 * P002005 / P001001)) + 
  geom_sf() + 
  scale_fill_viridis_c(option = "plasma",
                         direction = -1) + 
  labs(title = "Rural geography of the United States",
         caption = "Source: Census 2010",
         fill = "Percent Rural") +
    theme_void() 

rural_shifted
```


